GranjaAppService-main/Granja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('productos.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GranjaAppService-main/mainapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('inicio/', views.index, name='inicio'),  # Cambiado a 'inicio/' para distinguir de la vista de inicio de sesión
    path('iniciar_sesion/', views.iniciar_sesion, name='iniciar_sesion'),  # URL para el inicio de sesión
    path('registro/', views.registro, name='registro'),  # URL para el registro de usuarios
]

GranjaAppService-main/mainapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class TipoDocumento(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre')
    descripcion = models.CharField(max_length=250, verbose_name='Descripcion', blank=True, null=True)
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    actualizado = models.DateTimeField(auto_now=True, verbose_name='Actualizado')
    
    class Meta:
        verbose_name = 'Tipo de documento'
        verbose_name_plural = 'Tipos de documentos'
    
    def __str__(self):
        return self.nombre
    
class Personas(models.Model):
    tipoDocumento = models.ForeignKey(TipoDocumento, verbose_name="Tipo de documento", blank=True, on_delete=models.CASCADE, null=True)
    cedula = models.CharField(max_length=150, verbose_name='Cedula')
    user = models.OneToOneField(User, verbose_name="Usuario", blank=True, on_delete=models.CASCADE, null=True )
    imagen = models.ImageField(default='null', verbose_name="Imagen", upload_to="usuarios", null=True, blank=True)
    publico = models.BooleanField(verbose_name="Publicado?")
    fNacimiento = models.DateField(null=True, blank=True, verbose_name="Fecha de Cumpleaños")
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    actualizado = models.DateTimeField(auto_now=True, verbose_name='Actualizado')
    
    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'
    
    def __str__(self):
        return self.cedula

GranjaAppService-main/productos/models.py
from django.db import models

# Create your models here.
class CategoriaProducto(models.Model):
    nombre = models.CharField(max_length=150, verbose_name='Nombre')
    descripcion = models.CharField(max_length=250, verbose_name='Descripcion', blank=True, null=True)
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    actualizado = models.DateTimeField(auto_now=True, verbose_name='Actualizado')
    
    class Meta:
        verbose_name = 'Categoria Producto'
        verbose_name_plural = 'Categorias Productos'
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    categoria = models.ForeignKey(CategoriaProducto, verbose_name="Categoria", blank=True, on_delete=models.CASCADE, null=True)
    nombre = models.CharField(max_length=250, verbose_name='Nombre')
    cantidad = models.CharField(max_length=150, verbose_name='Cantidad')
    precio = models.CharField(max_length=150, verbose_name='Costo')
    descripcion = models.TextField(verbose_name='Descripcion', blank=True, null=True)
    imagen = models.ImageField(default='null', verbose_name="Imagen", upload_to="productos", null=True, blank=True)
    publico = models.BooleanField(verbose_name="Publicado?")
    fLote = models.DateField(null=True, blank=True, verbose_name="Fecha de Lote")
    creado = models.DateTimeField(auto_now_add=True, verbose_name='Creado')
    actualizado = models.DateTimeField(auto_now=True, verbose_name='Actualizado')
    
    class Meta:
        verbose_name = 'Producto'
        verbose_name_plural = 'Productos'
    
    def __str__(self):
        return self.nombre

GranjaAppService-main/mainapp/forms.py
from django import forms

class CustomUserCreationForm(forms.Form):
    username = forms.CharField(max_length=150)
    email = forms.EmailField(max_length=254)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return cleaned_data

GranjaAppService-main/mainapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse
from productos.models import Producto, CategoriaProducto
from .forms import CustomUserCreationForm

def index(request):
    categorias = CategoriaProducto.objects.all()
    productos = Producto.objects.filter(publico=True)
    # Verifica si el usuario ha iniciado sesión
    if request.user.is_authenticated:
        # Si el usuario está autenticado, obtén todos los productos
        productos = Producto.objects.all()
    cattmp = Producto.objects.filter(categoria=1)
    return render(request, 'mainapp/index.html', {
        'titulo': 'Home',
        'categorias': categorias,
        'productos': productos,
        'cattmp': cattmp
    })

def iniciar_sesion(request):
    if request.method == 'POST':
        # Si se envió el formulario de inicio de sesión
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Si la autenticación es exitosa, vuelve a cargar la página actual
            return render(request, 'mainapp/index.html')
        else:
            # Manejar el caso en que la autenticación falla
            # Por ejemplo, puedes mostrar un mensaje de error
            error_message = 'Usuario o contraseña incorrectos'
            return render(request, 'mainapp/index.html', {'error_message': error_message})
    else:
        # Manejar la solicitud GET (mostrar el formulario de inicio de sesión)
        return render(request, 'mainapp/index.html')

def registro(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # Almacenar los datos del usuario en la sesión
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            if 'users' not in request.session:
                request.session['users'] = []
            request.session['users'].append({'username': username, 'email': email})
            return redirect(reverse('index'))  # Redirige a la página principal
    else:
        form = CustomUserCreationForm()
    return render(request, 'mainapp/registro.html', {'form': form})

GranjaAppService-main/mainapp/templates/mainapp/index.html
{% extends "layouts/layout.html" %}

{% block content %}
{% load static %}
<!-- Hero Start -->
<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-md-12 col-lg-7">
                <h4 class="mb-3 text-secondary">100% Organic Foods</h4>
                <h1 class="mb-5 display-3 text-primary">Organic Veggies & Fruits Foods</h1>
                <div class="position-relative mx-auto">
                    <input class="form-control border-2 border-secondary w-75 py-3 px-4 rounded-pill" type="number" placeholder="Search">
                    <button type="submit" class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-100" style="top: 0; right: 25%;">Submit Now</button>
                </div>
            </div>
            <div class="col-md-12 col-lg-5">
                <!-- Formulario de inicio de sesión -->
                <form method="post" action="{% url 'iniciar_sesion' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Nombre de usuario</label>
                        <input type="text" class="form-control" id="username" name="username" placeholder="Nombre de usuario">
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Contraseña</label>
                        <input type="password" class="form-control" id="password" name="password" placeholder="Contraseña">
                    </div>
                    <button type="submit" class="btn btn-primary">Iniciar sesión</button>
                </form>
                
                <!-- Botón de registro -->
                <a href="{% url 'registro' %}" class="btn btn-secondary mt-3">Registrarse</a>
            </div>
        </div>
    </div>
</div>
<!-- Hero End -->

<!-- Fruits Shop Start-->
<div class="container-fluid fruite py-5">
    <div class="container py-5">
        <div class="tab-class text-center">
            <div class="row g-4">
                <div class="col-lg-4 text-start">
                    <h1>Nuestros Productos</h1>
                </div>
                <div class="col-lg-8 text-end">
                    <ul class="nav nav-pills d-inline-flex text-center mb-5">
                        <li class="nav-item">
                            <a class="d-flex m-2 py-2 bg-light rounded-pill active" data-bs-toggle="pill" href="#tab-0">
                                <span class="text-dark" style="width: 130px;">Todas</span>
                            </a>
                        </li>
                        {% for categoria in categorias %}
                        <li class="nav-item">
                            <a class="d-flex py-2 m-2 bg-light rounded-pill" data-bs-toggle="pill" href="#tab-{{categoria.pk}}">
                                <span class="text-dark" style="width: 130px;">{{categoria.nombre}}</span>
                            </a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div id="tab-0" class="tab-pane fade show p-0 active">
                    <div class="row g-4">
                        <div class="col-lg-12">
                            <div class="row g-4">
                                {% for producto in productos %}
                                    <div class="col-md-6 col-lg-4 col-xl-3">
                                        <div class="rounded position-relative fruite-item">
                                            <div class="fruite-img">
                                                <img src="img/fruite-item-5.jpg" class="img-fluid w-100 rounded-top" alt="">
                                            </div>
                                            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">{{producto.categoria}}</div>
                                            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                                <h4>{{producto.nombre}}</h4>
                                                <p>{{producto.descripcion}}</p>
                                                <div class="d-flex justify-content-between flex-lg-wrap">
                                                    <p class="text-dark fs-5 fw-bold mb-0">{{producto.precio}} COP CLU/ Disponibles: {{producto.cantidad}}</p>
                                                    <a href="#" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Agregar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

                {% for categoria in categorias %}
                <div id="tab-{{categoria.pk}}" class="tab-pane fade show p-0">
                    <div class="row g-4">
                        <div class="col-lg-12">
                            <div class="row g-4">
                                {% for producto in categoria.producto_set.all %}
                                    <div class="col-md-6 col-lg-4 col-xl-3">
                                        <div class="rounded position-relative fruite-item">
                                            <div class="fruite-img">
                                                <img src="img/fruite-item-5.jpg" class="img-fluid w-100 rounded-top" alt="">
                                            </div>
                                            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">{{categoria.nombre}}</div>
                                            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                                <h4>{{producto.nombre}}</h4>
                                                <p>{{producto.descripcion}}</p>
                                                <div class="d-flex justify-content-between flex-lg-wrap">
                                                    <p class="text-dark fs-5 fw-bold mb-0">{{producto.precio}} COP CLU/ Disponibles: {{producto.cantidad}}</p>
                                                    <a href="#" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Agregar</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>      
    </div>
</div>
{% endblock content %}

GranjaAppService-main/mainapp/templates/mainapp/inicio_sesion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Iniciar sesión</title>
</head>
<body>
    <h1>Iniciar sesión</h1>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div>
            <label for="username">Nombre de usuario:</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="password">Contraseña:</label>
            <input type="password" id="password" name="password">
        </div>
        <button type="submit">Iniciar sesión</button>
    </form>

    <!-- Formulario de registro -->
    <h2>Crear cuenta</h2>
    <form method="post">
        {% csrf_token %}
        {{ registration_form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
</body>
</html>

GranjaAppService-main/mainapp/templates/mainapp/registro.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrarse</title>
</head>
<body>
    <h1>Registrarse</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrarse</button>
    </form>
</body>
</html>